title: Create A Music Box
hero_image: images/banner.jpg
description: musicbox description
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
  - title: Introduction
  - title: What you will need
  - title: Turning a block into a box
